services:
  train:
    build:
      context: ..
      dockerfile: docker/Dockerfile.train
    container_name: crbot-train
    volumes:
      - ../:/app
    working_dir: /app
    command: python -m src.train

  runtime:
    build:
      context: ..
      dockerfile: docker/Dockerfile.runtime
    container_name: crbot-runtime
    volumes:
      - ../:/app
    working_dir: /app
    command: python -m src.runtime
